version: "3.7"

services:
  router01:
    container_name: router01
    hostname: router01
    image: frrouting/frr
    cap_add:
      - ALL
    volumes:
      - ./routers/router01:/etc/frr
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      net01:
        ipv4_address: 192.168.201.10
      net02:
        ipv4_address: 192.168.202.10
  router02:
    container_name: router02
    hostname: router02
    image: frrouting/frr
    cap_add:
      - ALL
    volumes:
      - ./routers/router02:/etc/frr
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      net02:
        ipv4_address: 192.168.202.20
      net03:
        ipv4_address: 192.168.203.20
  webserver:
    container_name: webserver
    hostname: webserver
    build: 
      context: .
    command: bash -c "ip route add 192.168.200.0/21 via 192.168.203.20 && python3 -m http.server 80"
    cap_add:
      - ALL
    networks:
      net03:
        ipv4_address: 192.168.203.100
  attacker:
    container_name: attacker
    hostname: attacker
    build: 
      context: .
    command: bash -c "ip route add 192.168.200.0/21 via 192.168.201.10 && tail -F anything"
    environment:
      - PYTHONUNBUFFERED=1
    cap_add:
      - ALL
    volumes:
      - .:/data
    networks:
      net01:
        ipv4_address: 192.168.201.200
  victim:
    container_name: victim
    hostname: victim
    build: 
      context: .
    command: bash -c "ip route add 192.168.200.0/21 via 192.168.201.10 && while true; do curl http://192.168.203.100; sleep 10; done"
    environment:
      - PYTHONUNBUFFERED=1
    cap_add:
      - ALL
    networks:
      net01:
        ipv4_address: 192.168.201.100

networks:
  net01:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-net01
    ipam:
      config:
        - subnet: 192.168.201.0/24
  net02:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-net02
    ipam:
      config:
        - subnet: 192.168.202.0/24
  net03:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-net03
    ipam:
      config:
        - subnet: 192.168.203.0/24
